### ISSUE TITLE
Improvement idea

### ISSUE THREAD

**Issue by r4gor** [raul-404/video-to-slides#7]
Wouldn't it be better for performance to skip a few seconds instead of skipping 60 frames?
Related to #1

**Comment by r4gor** [comment]
Che ne pensi @Ghiiso ?

**Comment by Ghiiso** [comment]
yes that was the idea but I swapped skipFrames and FrameSkipper while cleaning the code. ` READ_EVERY_N_FRAMES`  in ` config.yml` serves that purpose.

**Comment by Ghiiso** [comment]
o leggere ogni n frame oppure ogni n secondi
